<Workspace Version="1.3.4.6666" X="-249.40021452309" Y="-351.963590004886" zoom="1.49364430808002" ScaleFactor="1" Name="Get Parameter Names" Description="Retrieves the parameter names from element or element type." ID="c0ec0755-49d1-45bf-89d7-b8da72a3f7c0" Category="Teascripts.Parameter.Get">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ea3a82dd-2dd0-4024-8413-eb6fafff7724" type="PythonNodeModels.PythonNode" nickname="Python Script" x="519.177402562849" y="399.573189014846" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>
import clr

clr.AddReference('ProtoGeometry')

from Autodesk.DesignScript.Geometry import *


element = UnwrapElement(IN[0])

out = map(lambda parameter: parameter.Definition.Name, element.Parameters)

OUT = out
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7c5f5411-6884-4d0f-a545-c8d98fa122c0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="681.644649591203" y="401.341866495954" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="list of parameter names" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9947e78e-2419-4a85-a1f8-5d5d5b9c34c6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="232.62395824852" y="400.173012631643" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element or element type" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ea3a82dd-2dd0-4024-8413-eb6fafff7724" start_index="0" end="7c5f5411-6884-4d0f-a545-c8d98fa122c0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9947e78e-2419-4a85-a1f8-5d5d5b9c34c6" start_index="0" end="ea3a82dd-2dd0-4024-8413-eb6fafff7724" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>