<Workspace Version="1.3.4.6666" X="-1128.06052476155" Y="-628.592612273917" zoom="2.45244625" ScaleFactor="1" Name="Get Basic Wall Types" Description="Retrieves all the basic wall types in the project model." ID="e4f231e7-ef1f-4ae7-8249-7570ba1af02d" Category="Teascripts.Collections.Walls">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ee76caf3-cb81-4439-a017-9ada2fc2ac42" type="PythonNodeModels.PythonNode" nickname="Python Script" x="538.4" y="363.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager as DM

doc = DM.Instance.CurrentDBDocument

wallTypes = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Walls).OfClass(WallType).ToElements()
			
basicWalls = filter(lambda w: w.Kind == WallKind.Basic, wallTypes)

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = basicWalls</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6f42548d-2523-4c99-9479-9e0c9dda30f8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="684.679519370561" y="367.161724951916" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Basic Wall Types" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ee76caf3-cb81-4439-a017-9ada2fc2ac42" start_index="0" end="6f42548d-2523-4c99-9479-9e0c9dda30f8" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>